//! Coefficient-generic algebra in a basis cyclically generated by one operator.
//!
//! Both projective-bundle and negative-split three-point reconstruction use a
//! flat basis whose first vector is the unit and an operator whose powers of
//! that unit form a basis.  This module owns that target-neutral linear
//! algebra, including the change to cyclic coordinates and multiplication by
//! an element already expressed in those coordinates.

use crate::algebra::Coeff;
use crate::error::GwError;
use crate::series::{QSeries, SeriesMatrix};

use super::invert_series_matrix_coeff;

/// Coordinates in the q-dependent cyclic basis `(1, D, D^2, ...)`.
///
/// Keeping these coordinates distinct from an ordinary flat-basis vector
/// prevents callers from accidentally feeding the output of one
/// representation into multiplication expecting the other.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CyclicCoordinates<C: Coeff> {
    coefficients: Vec<QSeries<C>>,
}

/// A truncated quantum algebra generated by one multiplication operator.
///
/// The operator is represented in a flat basis whose coordinate zero is the
/// unit. Construction verifies that its powers generate the full state space
/// and caches the inverse change-of-basis matrix.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CyclicQuantumAlgebra<C: Coeff> {
    context: String,
    generator: SeriesMatrix<C>,
    cyclic_basis_inverse: SeriesMatrix<C>,
    dimension: usize,
    q_degree: usize,
}

impl<C: Coeff> CyclicQuantumAlgebra<C> {
    /// Validate and construct a cyclic algebra from multiplication by its
    /// chosen generator.
    pub(crate) fn try_new(
        generator: SeriesMatrix<C>,
        context: impl Into<String>,
    ) -> Result<Self, GwError> {
        let context = context.into();
        let rows = generator.rows();
        let cols = generator.cols();
        if rows == 0 {
            return Err(GwError::ConventionMismatch(format!(
                "{context} requires a nonempty multiplication matrix"
            )));
        }
        if rows != cols {
            return Err(GwError::ConventionMismatch(format!(
                "{context} multiplication matrix must be square, got {rows}x{cols}"
            )));
        }

        let q_degree = generator.max_degree();
        let cyclic_basis = cyclic_basis_matrix(&generator, rows, q_degree);
        let cyclic_basis_inverse =
            invert_series_matrix_coeff(&cyclic_basis).map_err(|error| match error {
                GwError::NonSemisimplePoint => GwError::ConventionMismatch(format!(
                    "{context} does not generate an invertible cyclic basis from the flat-basis unit"
                )),
                other => GwError::AlgebraFailure(format!(
                    "{context} cyclic-basis inversion failed: {other}"
                )),
            })?;

        Ok(Self {
            context,
            generator,
            cyclic_basis_inverse,
            dimension: rows,
            q_degree,
        })
    }

    /// Express a flat-basis vector in `(1, D, D^2, ...)` coordinates.
    pub(crate) fn coordinates(
        &self,
        vector: &[QSeries<C>],
    ) -> Result<CyclicCoordinates<C>, GwError> {
        self.validate_vector("flat-basis input", vector)?;
        Ok(CyclicCoordinates {
            coefficients: apply_matrix(&self.cyclic_basis_inverse, vector, self.q_degree),
        })
    }

    /// Multiply a cyclic-coordinate left factor by a flat-basis right factor.
    pub(crate) fn left_product(
        &self,
        left: &CyclicCoordinates<C>,
        right: &[QSeries<C>],
    ) -> Result<Vec<QSeries<C>>, GwError> {
        self.validate_vector("cyclic-coordinate left factor", &left.coefficients)?;
        self.validate_vector("flat-basis right factor", right)?;

        let mut result = vec![QSeries::<C>::zero(self.q_degree); self.dimension];
        let mut generator_power_right = right.to_vec();
        for (power, coefficient) in left.coefficients.iter().enumerate() {
            if !coefficient.is_structurally_zero() {
                for row in 0..self.dimension {
                    result[row].add_product_assign(&generator_power_right[row], coefficient);
                }
            }
            if power + 1 < self.dimension {
                generator_power_right =
                    apply_matrix(&self.generator, &generator_power_right, self.q_degree);
            }
        }
        Ok(result)
    }

    fn validate_vector(&self, role: &str, vector: &[QSeries<C>]) -> Result<(), GwError> {
        if vector.len() != self.dimension {
            return Err(GwError::ConventionMismatch(format!(
                "{} {role} has dimension {}, expected {}",
                self.context,
                vector.len(),
                self.dimension
            )));
        }
        if let Some((coordinate, actual)) = vector
            .iter()
            .enumerate()
            .map(|(coordinate, series)| (coordinate, series.max_degree()))
            .find(|(_, degree)| *degree != self.q_degree)
        {
            return Err(GwError::ConventionMismatch(format!(
                "{} {role} coordinate {coordinate} has q-truncation {actual}, expected {}",
                self.context, self.q_degree
            )));
        }
        Ok(())
    }
}

fn cyclic_basis_matrix<C: Coeff>(
    generator: &SeriesMatrix<C>,
    dimension: usize,
    q_degree: usize,
) -> SeriesMatrix<C> {
    let mut columns = Vec::with_capacity(dimension);
    let mut current = vec![QSeries::<C>::zero(q_degree); dimension];
    current[0] = QSeries::<C>::one(q_degree);
    for _ in 0..dimension {
        columns.push(current.clone());
        current = apply_matrix(generator, &current, q_degree);
    }
    SeriesMatrix::from_entries(
        (0..dimension)
            .map(|row| columns.iter().map(|column| column[row].clone()).collect())
            .collect(),
    )
}

fn apply_matrix<C: Coeff>(
    matrix: &SeriesMatrix<C>,
    vector: &[QSeries<C>],
    q_degree: usize,
) -> Vec<QSeries<C>> {
    (0..matrix.rows())
        .map(|row| {
            let mut total = QSeries::<C>::zero(q_degree);
            for (col, vector_coefficient) in vector.iter().enumerate() {
                let matrix_coefficient = matrix.entry(row, col);
                if vector_coefficient.is_structurally_zero()
                    || matrix_coefficient.is_structurally_zero()
                {
                    continue;
                }
                total.add_product_assign(matrix_coefficient, vector_coefficient);
            }
            total
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algebra::Rational;

    fn constant_vector(values: &[i64], q_degree: usize) -> Vec<QSeries<Rational>> {
        values
            .iter()
            .map(|value| QSeries::constant(Rational::from(*value), q_degree))
            .collect()
    }

    #[test]
    fn cyclic_coordinates_and_left_product_recover_companion_algebra() {
        // Multiplication by x in Q[x]/(x^2 - 2), in the basis (1, x).
        let generator = SeriesMatrix::constant(
            vec![
                vec![Rational::zero(), Rational::from(2)],
                vec![Rational::one(), Rational::zero()],
            ],
            0,
        );
        let algebra = CyclicQuantumAlgebra::try_new(generator, "test companion operator").unwrap();
        let left = algebra.coordinates(&constant_vector(&[2, 3], 0)).unwrap();
        let product = algebra
            .left_product(&left, &constant_vector(&[5, 7], 0))
            .unwrap();

        // (2 + 3x)(5 + 7x) = 52 + 29x when x^2 = 2.
        assert_eq!(product, constant_vector(&[52, 29], 0));
    }

    #[test]
    fn cyclic_product_respects_novikov_truncation() {
        // Multiplication by x in Q[[q]][x]/(x^2 - q).
        let q_degree = 1;
        let generator = SeriesMatrix::from_entries(vec![
            vec![QSeries::zero(q_degree), QSeries::q(q_degree)],
            vec![QSeries::one(q_degree), QSeries::zero(q_degree)],
        ]);
        let algebra =
            CyclicQuantumAlgebra::try_new(generator, "q-dependent test operator").unwrap();
        let x = constant_vector(&[0, 1], q_degree);
        let left = algebra.coordinates(&x).unwrap();
        let product = algebra.left_product(&left, &x).unwrap();

        assert_eq!(product, vec![QSeries::q(q_degree), QSeries::zero(q_degree)]);
    }

    #[test]
    fn construction_rejects_invalid_or_noncyclic_operators_with_context() {
        let empty = SeriesMatrix::<Rational>::zero(0, 0, 0);
        let error = CyclicQuantumAlgebra::try_new(empty, "empty test").unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message) if message.contains("empty test") && message.contains("nonempty")
        ));

        let nonsquare = SeriesMatrix::<Rational>::zero(2, 1, 0);
        let error = CyclicQuantumAlgebra::try_new(nonsquare, "shape test").unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message) if message.contains("shape test") && message.contains("2x1")
        ));

        let noncyclic = SeriesMatrix::<Rational>::zero(2, 2, 0);
        let error = CyclicQuantumAlgebra::try_new(noncyclic, "nil test").unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message)
                if message.contains("nil test") && message.contains("invertible cyclic basis")
        ));
    }

    #[test]
    fn vector_shape_and_truncation_mismatches_are_fallible() {
        let q_degree = 1;
        let generator = SeriesMatrix::from_entries(vec![
            vec![QSeries::zero(q_degree), QSeries::q(q_degree)],
            vec![QSeries::one(q_degree), QSeries::zero(q_degree)],
        ]);
        let algebra = CyclicQuantumAlgebra::try_new(generator, "dimension test").unwrap();

        let error = algebra
            .coordinates(&constant_vector(&[1], q_degree))
            .unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message)
                if message.contains("dimension test") && message.contains("dimension 1, expected 2")
        ));

        let error = algebra
            .coordinates(&constant_vector(&[1, 0], 0))
            .unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message)
                if message.contains("dimension test") && message.contains("q-truncation 0, expected 1")
        ));

        let left = algebra
            .coordinates(&constant_vector(&[1, 0], q_degree))
            .unwrap();
        let error = algebra
            .left_product(&left, &constant_vector(&[1], q_degree))
            .unwrap_err();
        assert!(matches!(
            error,
            GwError::ConventionMismatch(message)
                if message.contains("flat-basis right factor") && message.contains("dimension 1, expected 2")
        ));
    }
}
