//! A calibration adapter and its generic semisimple provider.
//!
//! A [`GwTarget`] combines one canonical [`GwTheory`] with the reconstruction
//! data that are specific to a semisimple calibration: the classical
//! eigenvalue seeds of divisor multiplication at the torus fixed points and
//! the quantum/classical divisor multiplication matrices.  Geometry such as
//! dimension, the effective cone, and first-Chern pairings is never restated
//! by this adapter.  [`TargetProvider`] turns any such calibration into a
//! [`SemisimpleCohftProvider`] by running the quantum-ring recipe: Newton
//! root series -> Lagrange canonical frame -> Bernoulli asymptotics from the
//! seed differences -> flatness recursion, and the descendant `S`-matrix from
//! the quantum differential equation.
//!
//! Current scope (deliberate, documented restrictions):
//!
//! - one Novikov variable (curve-class rank one); rank-two targets such as
//!   `P^n x P^m` need the multi-parameter series layer first;
//! - the state space is generated by a single divisor class with the flat
//!   basis `1, D, ..., D^rank-1`, so idempotents come from Lagrange
//!   interpolation and the metric is the residue pairing of the presentation.
//!
//! [`ProjectiveTarget`] is the reference implementation; the crate's original
//! `ProjectiveSpaceProvider` remains the production path and the two are held
//! equal by tests.

use super::*;
use crate::theory::{CurveClass, CurveEffectivity, GwTheory, ProjectiveSpaceTheory};

/// Semisimple calibration data attached to one canonical target theory.
pub trait GwTarget: Send + Sync {
    /// The sole geometric authority used by the reconstruction adapter.
    fn canonical_theory(&self) -> &dyn GwTheory;

    /// Unique identifier (including parameters) for calibration caches.
    fn cache_key(&self) -> String;

    /// Classical eigenvalues of divisor multiplication — the restrictions of
    /// the divisor to the torus fixed points.  Must be pairwise distinct
    /// (semisimplicity of the classical ring); their differences also feed
    /// the classical `R`-asymptotics.
    fn classical_eigenvalue_seeds(&self) -> Vec<RatFun>;

    /// Multiplication by the divisor generator in the flat basis, quantum or
    /// classical.  With the divisor-power flat basis this is a companion
    /// matrix whose last column is the (quantum) ring relation.
    fn divisor_multiplication(
        &self,
        q_degree: usize,
        quantum: bool,
    ) -> Result<SeriesMatrix, GwError>;

    /// Flat-basis coefficients of a user-facing insertion class.
    fn insertion_vector(
        &self,
        class: &crate::geometry::CohomologyClass,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError>;
}

/// Generic [`SemisimpleCohftProvider`] over any [`GwTarget`].
#[derive(Debug, Clone)]
pub struct TargetProvider<T> {
    target: T,
}

fn rank_one_curve(theory: &dyn GwTheory, degree: usize) -> Result<CurveClass, GwError> {
    if theory.curve_class_space().rank() != 1 {
        return Err(GwError::ConventionMismatch(
            "the generic target calibration requires a rank-one curve lattice".to_string(),
        ));
    }
    let degree = i64::try_from(degree).map_err(|_| {
        GwError::UnsupportedInvariant(
            "Novikov degree does not fit the canonical signed curve lattice".to_string(),
        )
    })?;
    Ok(CurveClass::new(vec![degree]))
}

impl<T: GwTarget> TargetProvider<T> {
    pub fn new(target: T) -> Self {
        Self { target }
    }

    pub fn target(&self) -> &T {
        &self.target
    }

    pub fn into_target(self) -> T {
        self.target
    }

    fn rank(&self) -> usize {
        self.target.canonical_theory().state_space().basis.len()
    }

    /// Monic characteristic polynomial of the quantum divisor multiplication,
    /// read off the companion matrix: `x^size - sum_k M[k][size-1] x^k`.
    fn quantum_charpoly(&self, q_degree: usize) -> Result<Vec<QSeries>, GwError> {
        let matrix = self.target.divisor_multiplication(q_degree, true)?;
        let size = matrix.rows();
        if size != self.rank() {
            return Err(GwError::ConventionMismatch(format!(
                "target divisor multiplication has rank {size}, but the canonical state space has rank {}",
                self.rank()
            )));
        }
        for col in 0..size.saturating_sub(1) {
            for row in 0..size {
                let expected = if row == col + 1 {
                    QSeries::one(q_degree)
                } else {
                    QSeries::zero(q_degree)
                };
                if matrix.entry(row, col) != &expected {
                    return Err(GwError::ConventionMismatch(
                        "target divisor multiplication is not in companion form; the \
                         divisor-power flat basis is required"
                            .to_string(),
                    ));
                }
            }
        }
        let mut charpoly = (0..size)
            .map(|row| matrix.entry(row, size - 1).neg())
            .collect::<Vec<_>>();
        charpoly.push(QSeries::one(q_degree));
        Ok(charpoly)
    }

    fn build_calibration(
        &self,
        q_degree: usize,
        z_order: usize,
    ) -> Result<SemisimpleCalibration, GwError> {
        let seeds = self.target.classical_eigenvalue_seeds();
        if seeds.len() != self.rank() {
            return Err(GwError::ConventionMismatch(format!(
                "target calibration has {} eigenvalue seeds, but the canonical state space has rank {}",
                seeds.len(),
                self.rank()
            )));
        }
        let charpoly = self.quantum_charpoly(q_degree)?;
        let roots = seeds
            .iter()
            .map(|seed| recipe::newton_root_series(&charpoly, seed, q_degree))
            .collect::<Result<Vec<_>, _>>()?;
        let frame = recipe::divisor_lagrange_frame(roots, q_degree)?;
        let classical_diagonal = seeds
            .iter()
            .enumerate()
            .map(|(branch, _)| {
                let differences = seeds
                    .iter()
                    .enumerate()
                    .filter(|&(other, _)| other != branch)
                    .map(|(_, other_seed)| other_seed - &seeds[branch])
                    .collect::<Vec<_>>();
                classical_r_asymptotics_for_point(&differences, z_order)
            })
            .collect::<Vec<_>>();
        calibration_from_canonical_frame(
            &frame,
            &classical_diagonal,
            q_degree,
            z_order,
            CalibrationId(format!("target-j:{}", self.target.cache_key())),
        )
    }
}

impl<T: GwTarget> SemisimpleCohftProvider for TargetProvider<T> {
    type Insertion = Insertion;

    fn colors(&self) -> usize {
        self.rank()
    }

    fn descendant_power(&self, insertion: &Self::Insertion) -> usize {
        insertion.descendant_power
    }

    fn insertion_degree(&self, insertions: &[Self::Insertion]) -> Option<usize> {
        let mut total = 0usize;
        for insertion in insertions {
            total = total.checked_add(insertion.descendant_power)?;
            total = total.checked_add(insertion.class.pure_power()?)?;
        }
        Some(total)
    }

    fn virtual_dimension(&self, genus: usize, degree: usize, markings: usize) -> Option<isize> {
        let theory = self.target.canonical_theory();
        let curve = rank_one_curve(theory, degree).ok()?;
        theory.virtual_dimension(genus, &curve, markings).ok()
    }

    fn degree_is_effective(&self, degree: usize) -> bool {
        let theory = self.target.canonical_theory();
        let Ok(curve) = rank_one_curve(theory, degree) else {
            return false;
        };
        !matches!(
            theory.effectivity(&curve),
            Ok(CurveEffectivity::Ineffective) | Err(_)
        )
    }

    fn expected_degree_from_dimension(
        &self,
        genus: usize,
        insertions: &[Self::Insertion],
    ) -> Option<usize> {
        let theory = self.target.canonical_theory();
        let zero = rank_one_curve(theory, 0).ok()?;
        let dimension_without_degree = theory
            .virtual_dimension(genus, &zero, insertions.len())
            .ok()? as i128;
        let insertion_degree = self.insertion_degree(insertions)? as i128;
        let generator = rank_one_curve(theory, 1).ok()?;
        let denominator = i128::from(theory.c1_pairing(&generator).ok()?);
        let numerator = insertion_degree - dimension_without_degree;
        if denominator <= 0 || numerator < 0 || numerator % denominator != 0 {
            return None;
        }
        let degree = usize::try_from(numerator / denominator).ok()?;
        self.degree_is_effective(degree).then_some(degree)
    }

    fn descendant_s_matrix(
        &self,
        q_degree: usize,
        z_order: usize,
    ) -> Result<SeriesSMatrix, GwError> {
        static CACHE: OnceLock<Mutex<HashMap<(String, usize, usize), SeriesSMatrix>>> =
            OnceLock::new();
        let key = (self.target.cache_key(), q_degree, z_order);
        let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
        if let Some(descendant_s) = cache.lock().unwrap().get(&key).cloned() {
            return Ok(descendant_s);
        }

        let quantum = self.target.divisor_multiplication(q_degree, true)?;
        let classical = self.target.divisor_multiplication(q_degree, false)?;
        let descendant_s = descendant_s_from_divisor_qde(
            &quantum,
            &classical,
            z_order,
            CalibrationId(format!("target-small-j:{}", self.target.cache_key())),
        )?;
        cache.lock().unwrap().insert(key, descendant_s.clone());
        Ok(descendant_s)
    }

    fn graph_kernel(
        &self,
        q_degree: usize,
        r_order: usize,
        graph_dimension: usize,
    ) -> Result<Arc<GiventalGraphKernel>, GwError> {
        static CACHE: OnceLock<
            Mutex<HashMap<(String, usize, usize, usize), Arc<GiventalGraphKernel>>>,
        > = OnceLock::new();
        let key = (self.target.cache_key(), q_degree, r_order, graph_dimension);
        let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
        if let Some(kernel) = cache.lock().unwrap().get(&key).cloned() {
            return Ok(kernel);
        }

        let calibration = self.build_calibration(q_degree, r_order)?;
        let kernel = Arc::new(GiventalGraphKernel::from_calibration(
            calibration,
            graph_dimension,
        )?);
        cache.lock().unwrap().insert(key, kernel.clone());
        Ok(kernel)
    }

    fn insertion_vector(
        &self,
        insertion: &Self::Insertion,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError> {
        self.target.insertion_vector(&insertion.class, q_degree)
    }
}

/// Projective space `P^n` as a [`GwTarget`]: the reference implementation.
///
/// `seeds` are the equivariant weights: the symbolic `lambda_i` for the fully
/// equivariant theory or rational constants for the specialized lambda-line
/// theory — the implementation is identical for both.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectiveTarget {
    theory: ProjectiveSpaceTheory,
    seeds: Vec<RatFun>,
}

impl ProjectiveTarget {
    pub fn equivariant(n: usize) -> Self {
        Self::try_equivariant(n).expect("projective calibration construction failed")
    }

    pub fn try_equivariant(n: usize) -> Result<Self, GwError> {
        let theory = ProjectiveSpaceTheory::try_new(n)?;
        let seeds = (0..theory.state_space().basis.len())
            .map(crate::algebra::lambda)
            .collect();
        Ok(Self { theory, seeds })
    }

    pub fn at_weights(n: usize, weights: &[Rational]) -> Self {
        Self::try_at_weights(n, weights).expect("projective calibration weights are invalid")
    }

    pub fn try_at_weights(n: usize, weights: &[Rational]) -> Result<Self, GwError> {
        let theory = ProjectiveSpaceTheory::try_new(n)?;
        let expected = theory.state_space().basis.len();
        if weights.len() != expected {
            return Err(GwError::ConventionMismatch(format!(
                "P^{n} calibration has {} weights, expected {expected}",
                weights.len()
            )));
        }
        let seeds = weights
            .iter()
            .map(|weight| RatFun::from_rational(weight.clone()))
            .collect();
        Ok(Self { theory, seeds })
    }

    pub fn n(&self) -> usize {
        self.theory.n()
    }

    pub fn theory(&self) -> &ProjectiveSpaceTheory {
        &self.theory
    }

    pub fn seeds(&self) -> &[RatFun] {
        &self.seeds
    }

    /// Coefficients of `prod_i (x - seed_i)` in ascending powers of `x`.
    fn classical_relation_polynomial(&self) -> Vec<RatFun> {
        let mut coefficients = vec![RatFun::one()];
        for seed in &self.seeds {
            let mut next = vec![RatFun::zero(); coefficients.len() + 1];
            for (power, coefficient) in coefficients.iter().enumerate() {
                next[power] = &next[power] - &(coefficient * seed);
                next[power + 1] = &next[power + 1] + coefficient;
            }
            coefficients = next;
        }
        coefficients
    }
}

impl GwTarget for ProjectiveTarget {
    fn canonical_theory(&self) -> &dyn GwTheory {
        &self.theory
    }

    fn cache_key(&self) -> String {
        let seeds = self
            .seeds
            .iter()
            .map(|seed| seed.to_string())
            .collect::<Vec<_>>()
            .join(",");
        format!("{}[{seeds}]", self.theory.theory_fingerprint())
    }

    fn classical_eigenvalue_seeds(&self) -> Vec<RatFun> {
        self.seeds.clone()
    }

    fn divisor_multiplication(
        &self,
        q_degree: usize,
        quantum: bool,
    ) -> Result<SeriesMatrix, GwError> {
        // Companion matrix for H-multiplication: H^{n+1} reduces via
        // prod_i(H - seed_i) = q (or 0 classically).
        let size = self.theory.state_space().basis.len();
        let relation = self.classical_relation_polynomial();
        let mut matrix = vec![vec![QSeries::zero(q_degree); size]; size];
        for col in 0..size.saturating_sub(1) {
            matrix[col + 1][col] = QSeries::one(q_degree);
        }
        for row in 0..size {
            matrix[row][size - 1] = QSeries::constant(relation[row].neg(), q_degree);
        }
        if quantum {
            matrix[0][size - 1] = matrix[0][size - 1].add(&QSeries::q(q_degree));
        }
        Ok(SeriesMatrix::from_entries(matrix))
    }

    fn insertion_vector(
        &self,
        class: &crate::geometry::CohomologyClass,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError> {
        let coeffs = class.coeffs();
        let expected = self.theory.state_space().basis.len();
        if coeffs.len() != expected {
            return Err(GwError::ConventionMismatch(format!(
                "P^{} insertion has {} coefficients, expected {}",
                self.n(),
                coeffs.len(),
                expected
            )));
        }
        Ok(coeffs
            .iter()
            .map(|coeff| QSeries::constant(coeff.clone(), q_degree))
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::CohomologyClass;
    use crate::tau;

    fn lambda_eval(value: &RatFun, target_n: usize, weights: &[Rational]) -> Rational {
        value
            .evaluate_lambda_weights(target_n, weights)
            .expect("generic test weights avoid poles")
    }

    #[test]
    fn target_provider_matches_projective_provider_calibration() {
        let weights = [Rational::from(2), Rational::from(5)];
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(1));
        let target_kernel = provider.graph_kernel(1, 3, 2).unwrap();
        let reference = projective_space_j_calibration(1, 1, 3).unwrap();
        let candidate = target_kernel.calibration();

        for order in 0..=3usize {
            let left = candidate.r_matrix.coefficient(order).unwrap();
            let right = reference.r_matrix.coefficient(order).unwrap();
            for row in 0..2 {
                for col in 0..2 {
                    for degree in 0..=1usize {
                        assert_eq!(
                            lambda_eval(left.entry(row, col).coeff(degree).unwrap(), 1, &weights),
                            lambda_eval(right.entry(row, col).coeff(degree).unwrap(), 1, &weights),
                            "R mismatch at z^{order} ({row},{col}) q^{degree}"
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn generic_projective_target_respects_point_effective_cone() {
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(0));
        assert!(provider.degree_is_effective(0));
        assert!(!provider.degree_is_effective(1));
        let formally_degree_one = [
            tau(1, CohomologyClass::one(0)),
            tau(0, CohomologyClass::one(0)),
            tau(0, CohomologyClass::one(0)),
        ];
        assert_eq!(
            provider.expected_degree_from_dimension(0, &formally_degree_one),
            None
        );
        assert!(provider
            .candidate_degrees_from_dimension(0, 2, &formally_degree_one)
            .is_empty());
    }

    #[test]
    fn target_provider_matches_projective_provider_descendant_s() {
        let weights = [Rational::from(2), Rational::from(5)];
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(1));
        let candidate = provider.descendant_s_matrix(1, 2).unwrap();
        let reference = projective_space_descendant_s_matrix(1, 1, 2).unwrap();
        for order in 0..=2usize {
            let left = candidate.coefficient(order).unwrap();
            let right = reference.coefficient(order).unwrap();
            for row in 0..2 {
                for col in 0..2 {
                    for degree in 0..=1usize {
                        assert_eq!(
                            lambda_eval(left.entry(row, col).coeff(degree).unwrap(), 1, &weights),
                            lambda_eval(right.entry(row, col).coeff(degree).unwrap(), 1, &weights),
                            "S mismatch at z^{order} ({row},{col}) q^{degree}"
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn target_provider_reproduces_known_invariants_at_weights() {
        // <tau_4(H)>_{2,1} on P^1 = 1/1920, through the generic target path
        // with rational seeds.
        let weights = [Rational::from(2), Rational::from(5)];
        let provider = TargetProvider::new(ProjectiveTarget::at_weights(1, &weights));
        let insertions = vec![tau(4, CohomologyClass::h_power(1, 1))];
        let value = compute_semisimple_graph_value(&provider, 2, 1, &insertions, None).unwrap();
        assert_eq!(value.as_rational(), Some(Rational::new(1, 1920)));

        // Degree-one line count on P^2 through two points and a line.
        let weights = [Rational::from(2), Rational::from(5), Rational::from(11)];
        let provider = TargetProvider::new(ProjectiveTarget::at_weights(2, &weights));
        let insertions = vec![
            tau(0, CohomologyClass::h_power(2, 2)),
            tau(0, CohomologyClass::h_power(2, 2)),
            tau(0, CohomologyClass::h_power(2, 1)),
        ];
        let value = compute_semisimple_graph_value(&provider, 0, 1, &insertions, None).unwrap();
        assert_eq!(value.as_rational(), Some(Rational::one()));
    }

    #[test]
    fn target_provider_symbolic_limits_to_known_invariant() {
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(1));
        let insertions = vec![tau(2, CohomologyClass::h_power(1, 1))];
        let value = compute_semisimple_graph_value(&provider, 1, 1, &insertions, None).unwrap();
        assert_eq!(
            value
                .nonequivariant_limit_line(1, &[Rational::from(2), Rational::from(3)])
                .unwrap(),
            Rational::new(1, 24)
        );
    }

    #[test]
    fn target_dimension_bookkeeping_matches_projective_provider() {
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(2));
        let reference = ProjectiveSpaceProvider::new(2, true);
        for genus in 0..3usize {
            for degree in 0..3usize {
                for markings in 0..4usize {
                    assert_eq!(
                        provider.virtual_dimension(genus, degree, markings),
                        reference.virtual_dimension(genus, degree, markings)
                    );
                }
            }
        }
        let insertions = vec![
            tau(1, CohomologyClass::h_power(2, 2)),
            tau(0, CohomologyClass::h_power(2, 1)),
        ];
        assert_eq!(
            provider.expected_degree_from_dimension(0, &insertions),
            reference.expected_degree_from_dimension(0, &insertions)
        );
    }

    #[test]
    fn target_adapter_uses_its_canonical_theory_for_all_geometry() {
        let target = ProjectiveTarget::equivariant(2);
        assert_eq!(target.n(), 2);
        assert_eq!(
            target.canonical_theory().theory_fingerprint(),
            target.theory().theory_fingerprint()
        );

        let provider = TargetProvider::new(target);
        for degree in 0..=3 {
            let curve = provider.target().theory().curve(degree);
            assert_eq!(
                provider.virtual_dimension(2, degree, 4),
                Some(
                    provider
                        .target()
                        .theory()
                        .virtual_dimension(2, &curve, 4)
                        .unwrap()
                )
            );
            assert_eq!(
                provider.degree_is_effective(degree),
                provider.target().theory().effectivity(&curve).unwrap()
                    != CurveEffectivity::Ineffective
            );
        }
    }

    #[test]
    fn projective_target_rejects_mismatched_calibration_rank() {
        let error = ProjectiveTarget::try_at_weights(2, &[Rational::from(1)]).unwrap_err();
        assert!(matches!(error, GwError::ConventionMismatch(_)));
    }

    #[test]
    fn provider_rank_is_canonical_and_mismatched_calibration_is_rejected() {
        let mut target = ProjectiveTarget::equivariant(2);
        target.seeds.pop();
        let provider = TargetProvider::new(target);
        assert_eq!(provider.colors(), 3);
        assert!(matches!(
            provider.graph_kernel(0, 1, 0),
            Err(GwError::ConventionMismatch(message))
                if message.contains("canonical state space has rank 3")
        ));
    }

    #[test]
    fn target_adapter_rejects_unrepresentable_novikov_degree_without_panicking() {
        let provider = TargetProvider::new(ProjectiveTarget::equivariant(1));
        if usize::BITS > i64::BITS {
            assert_eq!(provider.virtual_dimension(0, usize::MAX, 0), None);
            assert!(!provider.degree_is_effective(usize::MAX));
        }
    }
}
