//! A calibration adapter and its generic semisimple provider.
//!
//! A [`SemisimpleTarget`] combines one canonical [`GwTheory`] with the reconstruction
//! data that are specific to a semisimple calibration: the classical
//! eigenvalue seeds of divisor multiplication at the torus fixed points and
//! the quantum/classical divisor multiplication matrices.  Geometry such as
//! dimension, the effective cone, and first-Chern pairings is never restated
//! by this adapter.  [`TargetProvider`] turns any such calibration into a
//! [`SemisimpleCohftProvider`] by running the quantum-ring recipe: Newton
//! root series -> Lagrange canonical frame -> Bernoulli asymptotics from the
//! seed differences -> flatness recursion, and the descendant `S`-matrix from
//! the quantum differential equation. [`GwTarget`] preserves the original
//! projective-insertion contract and adapts into this generic boundary.
//!
//! Current scope (deliberate, documented restrictions):
//!
//! - one Novikov variable (curve-class rank one); rank-two targets such as
//!   `P^n x P^m` need the multi-parameter series layer first;
//! - the state space is generated by a single divisor class with the flat
//!   basis `1, D, ..., D^rank-1`, so idempotents come from Lagrange
//!   interpolation and the metric is the residue pairing of the presentation.
//!
//! [`ProjectiveTarget`] is the reference implementation; the crate's original
//! `ProjectiveSpaceProvider` remains the production path and the two are held
//! equal by tests.

use super::{
    calibration_from_canonical_frame, classical_r_asymptotics_for_point,
    descendant_s_from_divisor_qde, recipe, CalibrationId, GiventalGraphKernel,
    SemisimpleCalibration, SemisimpleCohftProvider, SeriesSMatrix,
};
use crate::core::algebra::RatFun;
use crate::core::bounded_cache::{BoundedCache, TARGET_RECONSTRUCTION_CACHE_CAPACITY};
use crate::core::error::GwError;
use crate::core::series::{QSeries, SeriesMatrix};
use crate::core::theory::{CurveClass, CurveEffectivity, GwTheory};
use crate::spaces::projective_space::Insertion;
use std::sync::{Arc, Mutex, OnceLock};

// Historical path: concrete targets are owned by their space modules.
pub use crate::spaces::projective_space::target::ProjectiveTarget;

/// Historical rank-one target contract with projective-space insertions.
///
/// Existing implementations remain source-compatible. New targets should
/// implement [`SemisimpleTarget`], whose insertion type is target-owned.
pub trait GwTarget: Send + Sync {
    fn canonical_theory(&self) -> &dyn GwTheory;

    fn cache_key(&self) -> String;

    fn classical_eigenvalue_seeds(&self) -> Vec<RatFun>;

    fn divisor_multiplication(
        &self,
        q_degree: usize,
        quantum: bool,
    ) -> Result<SeriesMatrix, GwError>;

    fn insertion_vector(
        &self,
        class: &crate::spaces::projective_space::CohomologyClass,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError>;
}

/// Insertion-generic semisimple calibration data attached to one canonical
/// target theory.
pub trait SemisimpleTarget: Send + Sync {
    /// User-facing insertion type translated by this target adapter.
    type Insertion;

    /// The sole geometric authority used by the reconstruction adapter.
    fn canonical_theory(&self) -> &dyn GwTheory;

    /// Unique identifier (including parameters) for calibration caches.
    fn cache_key(&self) -> String;

    /// Classical eigenvalues of divisor multiplication — the restrictions of
    /// the divisor to the torus fixed points.  Must be pairwise distinct
    /// (semisimplicity of the classical ring); their differences also feed
    /// the classical `R`-asymptotics.
    fn classical_eigenvalue_seeds(&self) -> Vec<RatFun>;

    /// Multiplication by the divisor generator in the flat basis, quantum or
    /// classical.  With the divisor-power flat basis this is a companion
    /// matrix whose last column is the (quantum) ring relation.
    fn divisor_multiplication(
        &self,
        q_degree: usize,
        quantum: bool,
    ) -> Result<SeriesMatrix, GwError>;

    /// Descendant exponent carried by a user-facing insertion.
    fn descendant_power(&self, insertion: &Self::Insertion) -> usize;

    /// Total cohomological-plus-descendant degree when the adapter can infer
    /// it. Returning `None` disables dimension-based degree selection without
    /// weakening the graph calculation itself.
    fn insertion_degree(&self, _insertions: &[Self::Insertion]) -> Option<usize> {
        None
    }

    /// Flat-basis coefficients of a user-facing insertion.
    fn insertion_vector(
        &self,
        insertion: &Self::Insertion,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError>;
}

impl<T: GwTarget> SemisimpleTarget for T {
    type Insertion = Insertion;

    fn canonical_theory(&self) -> &dyn GwTheory {
        GwTarget::canonical_theory(self)
    }

    fn cache_key(&self) -> String {
        GwTarget::cache_key(self)
    }

    fn classical_eigenvalue_seeds(&self) -> Vec<RatFun> {
        GwTarget::classical_eigenvalue_seeds(self)
    }

    fn divisor_multiplication(
        &self,
        q_degree: usize,
        quantum: bool,
    ) -> Result<SeriesMatrix, GwError> {
        GwTarget::divisor_multiplication(self, q_degree, quantum)
    }

    fn descendant_power(&self, insertion: &Self::Insertion) -> usize {
        insertion.descendant_power
    }

    fn insertion_degree(&self, insertions: &[Self::Insertion]) -> Option<usize> {
        let mut total = 0usize;
        for insertion in insertions {
            total = total.checked_add(insertion.descendant_power)?;
            total = total.checked_add(insertion.class.pure_power()?)?;
        }
        Some(total)
    }

    fn insertion_vector(
        &self,
        insertion: &Self::Insertion,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError> {
        GwTarget::insertion_vector(self, &insertion.class, q_degree)
    }
}

/// Generic [`SemisimpleCohftProvider`] over any [`SemisimpleTarget`].
#[derive(Debug, Clone)]
pub struct TargetProvider<T> {
    target: T,
}

fn rank_one_curve(theory: &dyn GwTheory, degree: usize) -> Result<CurveClass, GwError> {
    if theory.curve_class_space().rank() != 1 {
        return Err(GwError::ConventionMismatch(
            "the generic target calibration requires a rank-one curve lattice".to_string(),
        ));
    }
    let degree = i64::try_from(degree).map_err(|_| {
        GwError::UnsupportedInvariant(
            "Novikov degree does not fit the canonical signed curve lattice".to_string(),
        )
    })?;
    Ok(CurveClass::new(vec![degree]))
}

impl<T: SemisimpleTarget> TargetProvider<T> {
    pub fn new(target: T) -> Self {
        Self { target }
    }

    pub fn target(&self) -> &T {
        &self.target
    }

    pub fn into_target(self) -> T {
        self.target
    }

    fn rank(&self) -> usize {
        self.target.canonical_theory().state_space().basis.len()
    }

    /// Monic characteristic polynomial of the quantum divisor multiplication,
    /// read off the companion matrix: `x^size - sum_k M[k][size-1] x^k`.
    fn quantum_charpoly(&self, q_degree: usize) -> Result<Vec<QSeries>, GwError> {
        let matrix = self.target.divisor_multiplication(q_degree, true)?;
        let size = matrix.rows();
        if size != self.rank() {
            return Err(GwError::ConventionMismatch(format!(
                "target divisor multiplication has rank {size}, but the canonical state space has rank {}",
                self.rank()
            )));
        }
        for col in 0..size.saturating_sub(1) {
            for row in 0..size {
                let expected = if row == col + 1 {
                    QSeries::one(q_degree)
                } else {
                    QSeries::zero(q_degree)
                };
                if matrix.entry(row, col) != &expected {
                    return Err(GwError::ConventionMismatch(
                        "target divisor multiplication is not in companion form; the \
                         divisor-power flat basis is required"
                            .to_string(),
                    ));
                }
            }
        }
        let mut charpoly = (0..size)
            .map(|row| matrix.entry(row, size - 1).neg())
            .collect::<Vec<_>>();
        charpoly.push(QSeries::one(q_degree));
        Ok(charpoly)
    }

    fn build_calibration(
        &self,
        q_degree: usize,
        z_order: usize,
    ) -> Result<SemisimpleCalibration, GwError> {
        let seeds = self.target.classical_eigenvalue_seeds();
        if seeds.len() != self.rank() {
            return Err(GwError::ConventionMismatch(format!(
                "target calibration has {} eigenvalue seeds, but the canonical state space has rank {}",
                seeds.len(),
                self.rank()
            )));
        }
        let charpoly = self.quantum_charpoly(q_degree)?;
        let roots = seeds
            .iter()
            .map(|seed| recipe::newton_root_series(&charpoly, seed, q_degree))
            .collect::<Result<Vec<_>, _>>()?;
        let frame = recipe::divisor_lagrange_frame(roots, q_degree)?;
        let classical_diagonal = seeds
            .iter()
            .enumerate()
            .map(|(branch, _)| {
                let differences = seeds
                    .iter()
                    .enumerate()
                    .filter(|&(other, _)| other != branch)
                    .map(|(_, other_seed)| other_seed - &seeds[branch])
                    .collect::<Vec<_>>();
                classical_r_asymptotics_for_point(&differences, z_order)
            })
            .collect::<Vec<_>>();
        calibration_from_canonical_frame(
            &frame,
            &classical_diagonal,
            q_degree,
            z_order,
            CalibrationId(format!("target-j:{}", self.target.cache_key())),
        )
    }
}

impl<T: SemisimpleTarget> SemisimpleCohftProvider for TargetProvider<T> {
    type Insertion = T::Insertion;

    fn colors(&self) -> usize {
        self.rank()
    }

    fn descendant_power(&self, insertion: &Self::Insertion) -> usize {
        self.target.descendant_power(insertion)
    }

    fn insertion_degree(&self, insertions: &[Self::Insertion]) -> Option<usize> {
        self.target.insertion_degree(insertions)
    }

    fn virtual_dimension(&self, genus: usize, degree: usize, markings: usize) -> Option<isize> {
        let theory = self.target.canonical_theory();
        let curve = rank_one_curve(theory, degree).ok()?;
        theory.virtual_dimension(genus, &curve, markings).ok()
    }

    fn degree_is_effective(&self, degree: usize) -> bool {
        let theory = self.target.canonical_theory();
        let Ok(curve) = rank_one_curve(theory, degree) else {
            return false;
        };
        !matches!(
            theory.effectivity(&curve),
            Ok(CurveEffectivity::Ineffective) | Err(_)
        )
    }

    fn expected_degree_from_dimension(
        &self,
        genus: usize,
        insertions: &[Self::Insertion],
    ) -> Option<usize> {
        let theory = self.target.canonical_theory();
        let zero = rank_one_curve(theory, 0).ok()?;
        let dimension_without_degree = theory
            .virtual_dimension(genus, &zero, insertions.len())
            .ok()? as i128;
        let insertion_degree = self.insertion_degree(insertions)? as i128;
        let generator = rank_one_curve(theory, 1).ok()?;
        let denominator = i128::from(theory.c1_pairing(&generator).ok()?);
        let numerator = insertion_degree - dimension_without_degree;
        if denominator <= 0 || numerator < 0 || numerator % denominator != 0 {
            return None;
        }
        let degree = usize::try_from(numerator / denominator).ok()?;
        self.degree_is_effective(degree).then_some(degree)
    }

    fn descendant_s_matrix(
        &self,
        q_degree: usize,
        z_order: usize,
    ) -> Result<SeriesSMatrix, GwError> {
        static CACHE: OnceLock<Mutex<BoundedCache<(String, usize, usize), SeriesSMatrix>>> =
            OnceLock::new();
        let key = (self.target.cache_key(), q_degree, z_order);
        let cache = CACHE
            .get_or_init(|| Mutex::new(BoundedCache::new(TARGET_RECONSTRUCTION_CACHE_CAPACITY)));
        if let Some(descendant_s) = cache.lock().unwrap().get(&key).cloned() {
            return Ok(descendant_s);
        }

        let quantum = self.target.divisor_multiplication(q_degree, true)?;
        let classical = self.target.divisor_multiplication(q_degree, false)?;
        let descendant_s = descendant_s_from_divisor_qde(
            &quantum,
            &classical,
            z_order,
            CalibrationId(format!("target-small-j:{}", self.target.cache_key())),
        )?;
        cache.lock().unwrap().insert(key, descendant_s.clone());
        Ok(descendant_s)
    }

    fn graph_kernel(
        &self,
        q_degree: usize,
        r_order: usize,
        graph_dimension: usize,
    ) -> Result<Arc<GiventalGraphKernel>, GwError> {
        static CACHE: OnceLock<
            Mutex<BoundedCache<(String, usize, usize, usize), Arc<GiventalGraphKernel>>>,
        > = OnceLock::new();
        let key = (self.target.cache_key(), q_degree, r_order, graph_dimension);
        let cache = CACHE
            .get_or_init(|| Mutex::new(BoundedCache::new(TARGET_RECONSTRUCTION_CACHE_CAPACITY)));
        if let Some(kernel) = cache.lock().unwrap().get(&key).cloned() {
            return Ok(kernel);
        }

        let calibration = self.build_calibration(q_degree, r_order)?;
        let kernel = Arc::new(GiventalGraphKernel::from_calibration(
            calibration,
            graph_dimension,
        )?);
        cache.lock().unwrap().insert(key, kernel.clone());
        Ok(kernel)
    }

    fn insertion_vector(
        &self,
        insertion: &Self::Insertion,
        q_degree: usize,
    ) -> Result<Vec<QSeries>, GwError> {
        self.target.insertion_vector(insertion, q_degree)
    }
}
